### ISSUE TITLE
time long

### ISSUE THREAD

**Issue by LiangYat-sen** [bioinfkaustin/gromacs-on-colab#1]
**GROMACS is downloaded and compiled from source code. (This takes a while.)**
When I was performing this step, it took too long, even up to 3 hours. I found that manually downloading the linked file only took a few seconds.
Looking forward to your reply, thank you.
selection

**Comment by bioinfkaustin** [comment]
Hello @LiangYat-sen, thank you very much for your comment!

Yes, indeed, GROMACS has a very long compilation process. Unfortunately, the GROMACS project does not distribute any official pre-compiled binaries, [only source code](https://manual.gromacs.org/2023.2/download.html). However, since we know this tool runs only in Colab, it would be reasonable for us to distribute our own pre-compiled binary for Colab. As you suggest, this would make the installation a lot faster, which would be particularly helpful for free-tier Colab users. I will look into doing this soon (tracked at #2).
